# Default values for Kafka deployment
# This file is used when deploying Kafka via Helm charts

# Kafka cluster configuration
kafka:
  replicas: 3
  image:
    repository: bitnami/kafka
    tag: 3.4.0
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m
  storage:
    size: 10Gi
    className: gp2
  heapOpts: "-Xmx512m -Xms512m"

# Zookeeper configuration
zookeeper:
  replicas: 3
  image:
    repository: zookeeper
    tag: 3.8
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  storage:
    size: 10Gi
    className: gp2

# Service configuration
service:
  type: ClusterIP
  port: 9092